name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Roda todos os dias à meia-noite
  workflow_dispatch:  # Permite executar manualmente
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Gerar a animação
        uses: Platane/snk@v2
        with:
          github_user_name: michaeldsmartins
          outputs: dist/snake.svg

      - name: Adicionar o arquivo ao repositório
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
