name: Generate Snake Game

on:
  schedule:
    # Executa todos os dias às 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clona o repositório
      - uses: actions/checkout@v3

      # Configura Python para rodar o script
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      # Instala dependências necessárias
      - name: Install dependencies
        run: pip install requests

      # Gera o arquivo da animação da cobrinha
      - name: Generate Snake
        run: |
          curl -o snake.svg https://github.com/michaeldsmartins/snake-game/contributions?user=michaeldsmartins

      # Faz o commit da cobrinha gerada
      - name: Commit and Push Snake
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Updated Snake Game"
          git push
